### ISSUE TITLE
Using author name as an id

### ISSUE THREAD

**Issue by adamant-pwn** [ojacques/mkdocs-git-committers-plugin-2#7]
I'm somewhat worried about the fact that author's name is used as an id. There are some names that are quite common, so two different authors could have the same name. It seems that mkdocs-git-committers-plugin collects info for both commits and authors and in this way is able to map any author to its login. And here, for some reason, plugin sometimes fails to get an author's login. Is there anything that could be done about it?

**Comment by adamant-pwn** [comment]
Maybe another solution would be to get a single commit for each author in which they participated and get their login from that commit's info? Should still be ~1 API call per author, but this time login is almost certain to be obtained.

**Comment by josh-wong** [comment]
Thanks for the update.

I just tried using v0.4.4 to see if this issue of using the GitHub login as the author/contributor names is fixed, but it looks like the GitHub login isn't being checked. I'm still seeing someone else's profile picture, which links to their account instead of mine.

This is what the contents of my `authors.json` file looks like:

`{"[GITHUB_NAME]": {"login": "[GITHUB_NAME]", "name": "[GITHUB_NAME]", "url": "#", "avatar": "https://www.gravatar.com/avatar/..."`

If I manually change `"login": "[GITHUB_NAME]"` to `"login": [GITHUB_LOGIN]"` in `authors.json`, that doesn't solve the problem either. Instead, a new string is added with everything being `"login": "[GITHUB_NAME]"` being used again.

**Comment by ojacques** [comment]
> I'm still seeing someone else's profile picture, which links to their account instead of mine.

Thank you for the testing and the feedback. If the repository is public, can you point me to it? I'll have a look.

**Comment by josh-wong** [comment]
Absolutely. Here's the repo I've been testing it on:

- Repository: https://github.com/josh-wong/zune-software-setup
  - Site built on Material for MkDocs: https://josh-wong.github.io/zune-software-setup/

Let me know if there's anything I can do to help.

**Comment by ojacques** [comment]
> Absolutely. Here's the repo I've been testing it on:
> 
> * Repository: https://github.com/josh-wong/zune-software-setup

I tried with your repo, and the email used to do the commits `joshuarwong@outlook.com`  must be your primary email. I suspect that this is the problem.

> I've also tried to make my email address public since that seems to be how the plugin checks for GitHub login details, but that didn't work either (still shows a different account as the contributor).

Make sure you remove the cache file `.cache/plugin/git-committers/authors.json` - that could have been it.

> > Note
> > I found this plugin through the "Material for MkDocs Insider" program (active sponsor): [Document contributors | Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=contribu#document-contributors).

Nice!

Also, I agree that the current method of associating Git commits with Git users is not reliable. I started to put together some ideas on how to address this in #14.

**Comment by josh-wong** [comment]
> I tried with your repo, and the email used to do the commits j*****g@outlook.com must be your primary email. I suspect that this is the problem.

Gotcha. Let me try that in the next day or two and then report back.

In the meantime, could you please edit your previous reply and mask my email address? Just want to reduce spam where possible😅

**Comment by josh-wong** [comment]
>I tried with your repo, and the email used to do the commits j*****@outlook.com must be your primary email. I suspect that this is the problem.

I've confirmed that that email address is my primary email (check both my profile on the web and in GitHub Desktop). I tried changing my primary email address and re-ran the workflow to regenerate Material for MkDocs, but that didn't solve the issue.

>Make sure you remove the cache file .cache/plugin/git-committers/authors.json - that could have been it.

I've removed the cache each time I regenerate the docs locally, but that doesn't solve the issue either. I actually only see the default Gravatar profile picture that doesn't take me anywhere when I click it. I'm guessing that's something on my side, but it's only a minor issue right now.

---

# Successful, with caveats

I've had a bit of success on two separate instances of sites running on Material for MkDocs, but it took a bit of tinkering.

- [How to connect a Zune device to the Zune software](https://josh-wong.github.io/zune-software-setup/)
- [How to perform a hard reset of a TP-Link Wi-Fi router](https://josh-wong.github.io/tplink-router-hard-reset/)

## Caveat 1: Primary email address must be public

If I make my primary email address public, I appear as a contributor (profile pic and link to GitHub profile). Ideally, I'd like to not show my email publicly. In the personal access token configuration, I've tried giving access to the "user" scope, but I still need to show my email address publicly for me to appear as a contributor.

I assume some contributors don't have their primary email addresses publicly available. Is it possible to not show a primary email address publicly and still appear as a contributor?

## Caveat 2: Primary email address cannot be changed

If I change my primary email address on the "Email settings" page, on my GitHub profile, and in GitHub Desktop, I no longer appear as the contributor (gets the GitHub name rather than the GitHub login like before). If I change my email back to my original primary email address, I appear as the contributor again.

Is it possible to change my primary email address and still be able to appear as a contributor?

**Comment by ojacques** [comment]
@josh-wong thank you so much for the detailed feedback.
Can you try again with the latest (1.0.0) version of this plugin? With this version, no need to make your email address public. Let me know how it goes.

**Comment by josh-wong** [comment]
@ojacques Thanks for looking into it!

I've tried using the latest version (1.0.0) of the plugin, but I get the following error message when deploying.

```
Run mkdocs gh-deploy --force
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/mkdocs", line [8](https://github.com/josh-wong/zune-software-setup/runs/8133193976?check_suite_focus=true#step:5:9), in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 20[9](https://github.com/josh-wong/zune-software-setup/runs/8133193976?check_suite_focus=true#step:5:10), in gh_deploy_command
    cfg = config.load_config(
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/josh-wong/zune-software-setup/runs/8133193976?check_suite_focus=true#step:5:11).6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 224, in load_config
    errors, warnings = cfg.validate()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 132, in validate
    return self.run_validation(value)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 690, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 703, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/importlib/__init__.py", line [12](https://github.com/josh-wong/zune-software-setup/runs/8133193976?check_suite_focus=true#step:5:13)6, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line [18](https://github.com/josh-wong/zune-software-setup/runs/8133193976?check_suite_focus=true#step:5:19), in <module>
    from bs4 import BeautifulSoup as bs
ModuleNotFoundError: No module named 'bs4'
Error: Process completed with exit code 1.
```

When I specify version 0.4.4, the error doesn't occur, but I still need to have my primary email address public in order for my GitHub login to appear as contributor (like before).

**Comment by ojacques** [comment]
My bad. Fixed in 1.0.1 by #18

**Comment by josh-wong** [comment]
Sorry, I wrote that a few hours ago but didn't hit the "Comment" button until a few minutes ago. Just now saw that you released 1.0.1.

Deploy still fails on two separate repositories. I tried specifying the version in the `pip install` process as well, but that didn't work either. What's odd is that now I don't get a log of the error; all I see is "This check failed."

**Comment by josh-wong** [comment]
With the release of [v1.0.2](https://github.com/ojacques/mkdocs-git-committers-plugin-2/releases/tag/1.0.2) (referenced in #19) and some additional troubleshooting on my side, I've resolved the issue I mention in this issue by specifying the branch when it's not "main".

# Solution
In my last troubleshooting attempts, I didn't specify the branch (the default is "master", but I'm on "main"), even though I saw correct and incorrect contributors shown in my previous troubleshooting attempts. When using v1.0.2, I specified the "main" branch, which fixes my issue.

# Next steps
In the Material for MkDocs documentation for this plugin (https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=contribut#document-contributors), it mentions only adding the `repository` and `token` configuration options, and explicitly states the following:

> The other configuration options of this extension are not officially supported by Material for MkDocs, which is why they may yield unexpected results. Use them at your own risk.

I'll update the documentation for this plugin on Material for MkDocs  (`token` no longer necessary, but branch must be specified if not on the "master" branch).

Thank you for all your help, @ojacques! I really appreciate it🙇🏻‍♂️

**Comment by ojacques** [comment]
Glad it's working for you Josh. I also appreciate the precision of your comments and tests, and the willingness to make material for mkdocs even better!

I already have a PR for material for mkdocs. https://github.com/squidfunk/mkdocs-material/pull/4303.

See if it has the information you would have needed for your self.

**Comment by josh-wong** [comment]
Perfect! Your revisions are exactly what I had in mind. Thanks a bunch!
